version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: redbiidd_mood_journal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redbiidd_mood_journal
      MYSQL_DATABASE: redbiidd_mood_journal
      MYSQL_USER: redbiidd_mood_journal
      MYSQL_PASSWORD: redbiidd_mood_journal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
